services:
  sdk:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3369:3369"
    env_file:
      - ./env/app.env
      - ./env/blockchain.env
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:13.15-bullseye
    ports:
      - "5432:5432"
    env_file: 
      - ./env/database.env
