import {Column, Entity, PrimaryGeneratedColumn} from "typeorm"

/**
 * Represents a transaction entity in the database using TypeORM.
 * 
 * This entity maps to the 'transaction' table in the database and contains
 * information about transactions including sender, transaction hash, and gas details.
 */
@Entity('transaction')
export class TypeOrmTransaction {

    /**
     * Unique identifier for the transaction, auto-generated by the database.
     */
    @PrimaryGeneratedColumn()
    id: number;

    /**
     * Address of the sender of the transaction.
     */
    @Column()
    sender: string;

    /**
     * Hash of the transaction.
     */
    @Column()
    hash: string

    /**
     * The gas limit specified for the transaction.
     */
    @Column()
    gasLimit: string;
   
    /**
     * The maximum fee per gas unit specified for the transaction.
     */
    @Column()
    maxFeePerGas: string;
   
    /**
     * The maximum priority fee per gas unit specified for the transaction.
     */
    @Column()
    maxPriorityFeePerGas: string;

    /**
     * Constructs a new TypeOrmTransaction instance with optional initial values.
     * 
     * @param transaction - A partial object containing initial values for the entity properties.
     */
    constructor(transaction: Partial<TypeOrmTransaction>) {
        // Use Object.assign to copy properties from the partial object to this instance.
        Object.assign(this, transaction);
    }
    
}